name: prishathe
description:
publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  iconsax: ^0.0.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.6
  youtube_player_flutter: ^9.0.1
  font_awesome_flutter: ^10.7.0
  readmore: ^3.0.0
  video_player: ^2.8.5
  multi_image_picker_view: ^1.0.3
  http: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.8
  file_picker: ^8.0.0+1
  mime: ^1.0.5
  cached_network_image: ^3.3.1
  razorpay_flutter: ^1.3.6
  flutter_native_splash: ^2.3.10


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#42a5f5"
  background_image: "assets/images/Albert-Einstein.png"
  image: "assets/images/Login Image-01.png"

  android_12:

    image: "assets/images/Login Image-01.png"

  # Splash screen background color.
    color: "#42a5f5"

  # App icon background color.
    icon_background_color: "#111111"



flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/success/
    - assets/images/success/lady-adding-product-in-cart-animation.json
    - assets/images/success/payment failed.json
    - assets/images/success/processing.json
    - assets/images/user.png
    - assets/images/VideoThumbnail/
    - assets/images/blogImages/
    - assets/images/searchbackgroundvideo.mp4
    - assets/images/Shop Images/
    - assets/images/Image Thumbnail/
    - assets/icons/


